# Generated by Django 3.1 on 2020-08-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200816_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='questions',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='usersanswer',
            old_name='questions',
            new_name='question',
        ),
    ]
